"use client";
import { useCallback,useEffect,useState } from "react";
import { Banknote,LogOut,RefreshCw,Scale,Ticket,Trophy } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

type Resumo={data:string;totalPules:number;arrecadado:number;premios:number;resultado:number;vencedoras:Array<{codigo:string;modalidade:string;numeros:string[];valorPago:string;valorPremio:string}>;sorteio:null|{primeiro:number;segundo:number;terceiro:number;quarto:number;quinto:number}};
const hoje=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());
const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function AdminDashboard(){
  const router=useRouter();
  const [data,setData]=useState(hoje),[resumo,setResumo]=useState<Resumo|null>(null),[premios,setPremios]=useState(["","","","",""]),[mensagem,setMensagem]=useState(""),[loading,setLoading]=useState(true);
  const carregar=useCallback(async()=>{setLoading(true);setMensagem("");const response=await fetch(`/api/admin/resumo?data=${data}`,{cache:"no-store"});if(response.status===401){router.replace("/admin/login");return;}const body=await response.json();if(!response.ok)setMensagem(body.error);else setResumo(body);setLoading(false);},[data,router]);
  useEffect(()=>{const timer=setTimeout(()=>void carregar(),0);return()=>clearTimeout(timer);},[carregar]);
  async function sortear(){setMensagem("");const response=await fetch("/api/admin/sorteios",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data,premios:premios.map(Number)})});const body=await response.json();setMensagem(response.ok?`${body.apuradas} pule(s) apurada(s).`:body.error);if(response.ok)await carregar();}
  async function sair(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/admin/login");router.refresh();}
  return <main className="min-h-[100dvh] p-4 md:p-6"><header className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] pb-4"><div><p className="chalk text-3xl text-[var(--yellow)]">Fechamento da banca</p><p className="text-xs text-[var(--muted)]">Sorteio, apuração e caixa</p></div><div className="flex gap-2"><Link href="/" className="press grid min-h-12 place-items-center border border-[var(--line)] px-4 text-sm">Balcão</Link><button onClick={sair} className="press flex min-h-12 items-center gap-2 border border-[var(--line)] px-4 text-sm"><LogOut size={17}/> Sair</button></div></header><div className="mx-auto mt-5 grid max-w-6xl gap-5 lg:grid-cols-[1fr_1.2fr]">
    <section className="panel p-4 md:p-5"><div className="flex items-center justify-between"><div><h1 className="chalk text-3xl">Resultado do dia</h1><p className="text-sm text-[var(--muted)]">Informe os cinco milhares sorteados.</p></div><Trophy className="text-[var(--yellow)]"/></div><label className="mt-5 block text-sm">Data<input type="date" value={data} onChange={(e)=>setData(e.target.value)} className="mt-2 min-h-12 w-full border border-[var(--line)] bg-black/20 px-3 [color-scheme:dark]"/></label><div className="mt-4 grid grid-cols-5 gap-2">{premios.map((premio,i)=><label key={i} className="text-center text-xs text-[var(--muted)]">{i+1}º<input aria-label={`${i+1}º prêmio`} inputMode="numeric" maxLength={4} value={premio} onChange={(e)=>setPremios((p)=>p.map((v,j)=>j===i?e.target.value.replace(/\D/g,""):v))} className="mt-1 min-h-14 w-full border border-[var(--line)] bg-black/20 px-1 text-center text-lg text-white"/></label>)}</div><button disabled={premios.some((p)=>p.length!==4)||Boolean(resumo?.sorteio)} onClick={sortear} className="press mt-5 min-h-14 w-full bg-[var(--yellow)] px-3 font-bold text-[#15231d] disabled:opacity-40">{resumo?.sorteio?"SORTEIO JÁ FECHADO":"APURAR PULES"}</button><p aria-live="polite" className="mt-3 min-h-5 text-sm text-[var(--yellow)]">{mensagem}</p></section>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="chalk text-3xl">Caixa</h2><p className="text-sm text-[var(--muted)]">Resumo financeiro de {new Date(`${data}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><button onClick={carregar} aria-label="Atualizar resumo" className="press grid size-12 place-items-center border border-[var(--line)]"><RefreshCw className={loading?"animate-spin":""}/></button></div><div className="grid gap-3 sm:grid-cols-2"><Metric icon={Ticket} label="Pules" value={String(resumo?.totalPules??0)}/><Metric icon={Banknote} label="Arrecadado" value={brl(resumo?.arrecadado??0)}/><Metric icon={Trophy} label="Prêmios" value={brl(resumo?.premios??0)}/><Metric icon={Scale} label="Resultado" value={brl(resumo?.resultado??0)} accent={(resumo?.resultado??0)>=0}/></div>{resumo?.sorteio&&<div className="panel mt-3 p-4"><p className="text-xs uppercase text-[var(--muted)]">Prêmios lançados</p><p className="mt-2 text-xl font-bold tracking-[.12em] text-[var(--yellow)]">{[resumo.sorteio.primeiro,resumo.sorteio.segundo,resumo.sorteio.terceiro,resumo.sorteio.quarto,resumo.sorteio.quinto].map((n)=>String(n).padStart(4,"0")).join("  ")}</p></div>}{Boolean(resumo?.sorteio)&&<div className="panel mt-3 p-4"><h3 className="chalk text-2xl text-[var(--yellow)]">Pules premiadas</h3>{resumo?.vencedoras.length?<ul className="mt-3 space-y-2">{resumo.vencedoras.map((pule)=><li key={pule.codigo} className="grid grid-cols-[1fr_auto] gap-3 border-t border-[var(--line)] pt-2 text-sm"><span><b>{pule.codigo}</b><small className="block text-[var(--muted)]">{pule.modalidade} {pule.numeros.join(" + ")}</small></span><strong className="text-[var(--yellow)]">{brl(Number(pule.valorPremio))}</strong></li>)}</ul>:<p className="mt-2 text-sm text-[var(--muted)]">Nenhuma pule premiada neste sorteio.</p>}</div>}</section>
  </div></main>;
}
function Metric({icon:Icon,label,value,accent}:{icon:typeof Ticket;label:string;value:string;accent?:boolean}){return <div className="panel min-h-32 p-4"><Icon size={22} className="text-[var(--muted)]"/><p className="mt-5 text-xs uppercase text-[var(--muted)]">{label}</p><strong className={`mt-1 block text-2xl ${accent?"text-[var(--yellow)]":""}`}>{value}</strong></div>;}
